language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
sudo: required
services:
  - docker
notifications:
  email:
    - ngomalalibo@gmail.com
  on_success: always
  on_failure: always
env:
  global:
    - secure: mKRss8Vudu9SMmSyHLWvEdlnManwanN3JzK5jIKvNcb0vGGJESSvG8thOw09R3H5o+dSC0xGisP8C1VvTzn/V8wn53eOwcNB8h4G6pymIsWBT6oUHBlh/rSA/yuznJT3lM3TMjkJIs0dU1xYm7iz5ES0si1hAIDyJBbkrCBH2j/uK9v0nigQIUE7wtO1ppY8736rhf9rLE9uD1dZVJ1NQ6AWmapwvB0KB2finNiAdBImOo7CXcxc2bHkZ6ZfY17cgpZQEiiuXAooygvYxXrpJlkfH4vXqa9om5tjeleRPFBu4TAnQ7Qbu21s4VZuskh4rIgfd8NMImwTZCgfLslgLoYRUAxdi6vIwwMQ0SB/SKJpXlyMA9GYVrPkHsL19jeaCxOpxQwxr/UNSmO+tWnbrZtQvw2MRCOyqEZlpDQiEQ9kuAxmrAVLaOpcZL6eUXGXp+W8o6imQMYB7Zz5lO7m4n5gt1SaLRkWXWA6ukAITPwOUZzlsfTGVCdpPuZkf5lGpfOAEvWXDsWJ0Ac8gCqw3mJVSKfk0AAm9ykUnNK/AUqLJqD1W19ySrLKtUsn16ngSLrth1sJ/qFW0LUUyc2G5izlqbPnDhAqP1Wtct3RI4+joHfzHgf4VbeoUdIEykkI/SStjbJU2QxjZRL2j2l31IB2B0T5iO0tSNgPiZzhTTk=
    - secure: c2295ro7t2XT2WJBDgVdeYOyUBROkt+RMK+oUOHmB+LA+4i8SJoxDyWZ4MfehCFZXY4EsI3U6o2Q22I1xsFVuk3I9ddKP3vRQ6g84dBomtQyGkBwiYt1G9+L1e5QH/2RKpL8jmEMzWDALTLHQj1OXTBRbWBV5Q3XRzSaDVdSnJCn8axFnZ4W/t9CXEhIdV677i/wghYziZDert/qmzkTLknQmQ9jpkb7b2YbyfV9pVJ85/Xw0ADiGDvlpf2elvSxyExF+JJRC9W1mG3ifD1G3LC1KaqZ+gnz33Zi54WoCZ5QOXnpri+ozNUL9txCLaYhVuGUkp3cUF+cdNzpIsFbIpZ6Hk4GNfx3pplHapSS8priwdn0/1xpyvvUyaDL6GfswKF3WgxwW0BQPrKAIGKFBXHMORk7Etf5b+qQHwa30K7dpMAN6An//esiLXg2JDX5zPHVjJPkPs/kKxdN2a82pJtcik0ReC2kmK3DjDcxJxUGEerWGXTnzTBI31c+PkxqeqVDu276xk4hC5WcojzDh5Usv/ta0XgRiAXQqYT7qnJZ4H+1AHh/I42EDhOc333eZYjsqD712hnyUGYumIEkz2HD3aZHGac6/pv4fckAUYgR2EHEArZ/YRdzlBiq5+16oDH7shqgHKpCVQQ7tdudAUfk9Ga+/BPrN9fF79nv8cM=
    - secure: RF+WSqkHDTCYXBnbepYmUwCu/mZFyUJZ34qIAmaG7O9d0lF2aOeMkB2+zwF/LrkN1jZZiiBXRoLX06O0RhUDKcrmIZLnYOQHcbcYSNXE/wEGsfz+mMIVGVN1YKvjaWviuO4OubZNACgYhxYgdmN8/qNgLFWVNGgeO1jcfo3DR5puHEXCHxwn9howjtfX0Qcx7DDq5XTE3NHjEDUqVt73En6C8iCKspmcqgYSGdN1zjr5VKHK9kBjfD2Wla2AqVQHy/xdbkSSoxZlfFHl6dcbUiYDUpfK35ytZqLpgyvJbh30HzBhIsPuFDqEYLyR6+DFycHkH7kWxPzAWN/+XWdQm0zz0vPmDaFR6JETrVi9ig9D1uXIidt7biNjZTZTbb2hGVAlUOIvfky+pYQ4LogytuMFq/Smn4Buz5SGvkcNX+WybwzwAiCoHX2+B10viOoq3mhJubiQDut6co7DW+oVmW0xtcaJxwvPG2d8fVjRQoO8Y8CQH90u/NZ1xvfVCmB7/aTAnHEwxLeWCR4nGDbQhRVIywUmp/FQrH1IH6dlOFnyN8KPqALNgpEjBrfWQBVtvMUuGbEfngonJN+jedXKtcw9LUdZvN8KDM0YjJc8hNGDD/SDWw8DOXMQRctLWq4yetFhQwvXNae6s+jH+zUZR1jprf1hpc/986oUmVZFeBs=
    - secure: ADVdKU2VvMHNRZwHeR+90Rl2f9ilJD7iLus4vNEGRXMKZ+rY48KmE/lI2D5xYnpsJuiZz+iRsvugsJxyfRivzzb9aSmotsF1wt+Itg4iIwKXl614nS/46AM0gw8ZyRH26PkCa3YpviJ3W/SUdBq8+OaSK1e+oDyGaEnb3faJYAn3tfmFWkmUi5QtDQAp8BOsSSbXLcGfv30pgbWmjGqr/DrPgoCQbj6BKkke0ISH1JGzGIb6lY8ROcVFkuiR8kVwFBWPjjSG62vd4Fgv9siWKOKkbvCFDdJ8pd7f9yClRM+clFP1EWVO62kS1UgsKGWB0CysvnaLeL5b7OhZxmtfom42C14QdLsgmGtkyr7TcnviMoFpx73bDZZO5+4stx8aITxdQzc2cWO94V6mt5XTxOF0eV0NqzBzTI7Q/9G9aaMgsAauKIcv018B8DGD63QnvxIBH0om4dBWsNCDZg/p9MtrEoOkPvKsl3IAxTX57wNeNcuX6zjeMdabDgx4Sk8y9v6r+/ZKT/LWaCec0gZNaitRuj+Wiu16sgJp7O5c9RDUX+DO6nPlcelvNl1CcpeQ/fYGsIc5U4UFNwdxBOdCwNCntRRCCSBR/Ztuq997jjQXsM44AgDgkNWTTUbyLKarRKFYMAmmLVikl92Cqxrx7J91hXdiQLhIY4OFqImkRDQ=
    - secure: HtX4Wo6yGgnYO2JmTl7dnMF04n4Ke2kztCkap8oXA7PbdO8COvsI8fGi06fZ382O5GVjAT0tOEmwgiIl3nb2lVa5AsUcZQX8+GjJUrudvJKcE+UhajEu4uLlN56J2MnIhriA/vIPfdSol5mLmUQLjQLpDJvSlfOAGjNMUegFsjNqcduJTG8RcDA0oeheuYYcsiRuPN5nPG+boQN0Prmm87cd88vG9HgqGQYs6XmhmdOP2o2NlVCM5Wnexl4uXosAkobIfz/H8DtDZfedbSw2WdvnMH2ihsm4CaqbZHqsF4bStSCtEJHewuTqQvdjEHTZo+RRjeAayUBmQ+ijGYOSOGf3mfrN5eYgi4uoR6oPCr6WK2jv85zgNW94ZvjU0vcbaJcLUG2j5zVh4XCFNWCeLgm276oeZr1UUIrRkM9ZRUWLus+oDn/G/BvO7tY2bjmngxkSqh0Nh01aJfH2pKWgFFrNeNAa84N4ZJvDntKS0F8afCnx7XQR/ek41Sc1SQAMk702OeloTQ2mJWosJ4gTtezGU9byjdWWxJHNHWgsOlPSMJiaa09SzLmweYDfumhINmJa90v45bjyeFle9/Oy/qTo87yRMC1Vl3ZGwg463m5w7yBWWypdLdYg8HiBSyxPMNV+TELjmSHSuEv6zr5W0iHIx5wfzJCruBvpWMIonLs=
addons:
  ssh_known_hosts: ec2-3-64-125-172.eu-central-1.compute.amazonaws.com
before_install:
  - chmod +x mvnw
  - mvn clean install
  - export BUILD_NAME=stockquote-master-$(date -u "+%Y%m%d%H%M%S")
script:
  - sh travis_scripts/tag_build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i "all-stock-key-pair.pem" ubuntu@ec2-3-64-125-172.eu-central-1.compute.amazonaws.com 'bash launch_build.sh'
  on:
    branch: master
