language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
sudo: required
services:
  - docker
notifications:
  email:
    - ngomalalibo@gmail.com
  on_success: always
  on_failure: always
addons:
  ssh_known_hosts: ec2-3-64-125-172.eu-central-1.compute.amazonaws.com
before_install:
  - chmod +x mvnw
  - mvn clean install
  - export BUILD_NAME=stockquote-master-$(date -u "+%Y%m%d%H%M%S")
script:
  - sh travis_scripts/tag_build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i "all-stock-key-pair.pem" ubuntu@ec2-3-64-125-172.eu-central-1.compute.amazonaws.com
    'bash launch_build.sh'
  on:
    branch: master
env:
  global:
    - secure: ew/yOy1ORzAmPPkA0wO+2cWe0KumI0wvQMrcUz7duibM/9C/xDw3HAjSNmEFcGzbzaTTC1oED+Fwza8/4jI4Wy6MbRwEVjv/Q1opl+YLh2ye3SiqOSNJKI8QjOTCB6uoRhZz0Abjlp2pCjyatMPxZB0S2SA8oNx3SugNdbBQxDxhI0yqdiLShjfmo21c8eeu5tcKuZdAqC3BqaIcX7V4i75SOp+ktoIz+Nuz3YZYZLsjfNtzzQrKTUeuVEVj2tAxr79MFHRFZm31Hi2fy0qly22IuwglJjMdqGqAVy2NyggQl+F+16/zMZNepDvz2f+S0zJryKDSSsK7l5TdOEzwnxV72a+Zdx6W+tO57ttMutyjAXKVzJ0SOq3XmHz3C9fwuENYtCfiPm+9g8WOlWy9YEW+C5t6qogu+EqcYBik8P4zhDMUuxjUMFCDi0Al6007hWqsuPvWQPtBI2v6OiEIgWTwuOPceo+1fzJaQqPeTBmEClFo4P6E9Hsfdo5UuYZYu5Dd5hD/qVhJMNc0P9hctKleTM2SxDqfR3y+selIpCkl72vvqP8sOOnrqi0JfpNPNG4fTH0EfsFIDBqYx6/xu9Ql3MSZI0awVBZr1IMKcHyqhKp91sQ+fRzuE9r7Gr9nnVuLJ9xRYWqNdL8dqrmI17JZPby4kijdLYCbTvzRCZI=
    - secure: i+zkaP9886yHqL4zhxuYEzpOCOX3D34Vue/K0XpJN06JKII+7VpsnwCLilc0bHsI0Fkvn18WtCsCNaoul4Wy9FeLAPdVkFwdTHnMd5ysHH+F+iPNjaqS58780xp2BzoOYHFVSEZ7XwjAhWSKW1XyEFmAryhfEkKNDiDe1WwFGqn7m1Uu0MsC3u430nm9SnRLWxC71B5JaoSKgCS/EKUim3MkCYrrGOQG8aUNQal5q7VcuCThHTf2ndjOB6Dt0xzrWMxLCBLPA2XdDulo0jqZWxfLj3N+MCpGc248LimVYcS3g8gkS2JtaI6BskwTVT/VS7Uah26y1qfVsC0gN76TLK7jwnA/YrxXgKX6FjJodAYZ4+b84w3z3nVggi3yaOVd2BAhkPB0UhIMk3CzUR0RkMbE816/8l/DsiUS6bz7Obf01ZGeonLHxofrywyRvn/e3WuDNGjqU9sxvkhef/QCKZTHlMm2x8nuk45I3QJPZb+SMIhXOs0cQm7m47y05HN37JnFjdysjy1hRlOsJhCM+8tpHgWZBrACr4HmRoACXUu9dGL8vEmIGx5eGRz4ib0t7MgCwKs8YKUD16IMPg8ARMBV6X4eU1XxMtzaUQLRbLn3cbpPmHmAlZwqHufRCn6I0n+LAJ46hpzayiTZWEOHRMjygv6dXyw3LE8/d5QNzu8=
    - secure: nVeE64JXmUhrNynLe8fmoXanazHilLtWZ9r+rtQZI2D7gD4IEvpGjkv1PF28LZkT07jrySFruLlpg17yr9stXOkP9aSGdJ5FzQfLm4GoGjLmkbNcWS5vsQ5y8KqqWtYiemTSfDCq+2qs4SlnEO/PbgKXxUK3axADmzt54yhmqmMtIrSJ0nnDURy3SYZylfV0/2c5qIdLbIqWEtWWmxX/1+VLmtEb9az4+US0Kpx0oPL+HGDrUuHIXnnJHNycoC8ObNkKZARbTVf6k/iM7Mlu/vGz7wXFIomrp0P7dlYnsz78RX3vb9gBoRVhJJRv8uAmPsf3eLYSqZ5Auu1TYdMamiPQ725HRas0fldm9l/PwRGAE3o/TDd2pIPLw/GOmGYkBk6ycMANvGhgag4JnH8fwPSn+i5Ac8PXf5REygOjC6GOjDlRjnjtDdoiDXXmeth7GjlxRjsYM7YnwEw5SiUkouDcf/25nmOH8Eb04TjilKpDWcRIlccbWSeTa7qB4hTEgKzzcTN1omsNptFvKL/v8S9mre49GV8u608DqAcAHsrgOhipqRXNGudb7/FnxJAYHDeq4rUX966ZvtZP+dtqw48H7JypxUQOe+FNpups9t1/cn6WHdw+Yx5g6b+r6gUEKeeqdDkyELfrGw0HMZW7fL1ndEkvCUhgKLiX2hi6f+c=
    - secure: Orv/SCUU55DAquBohZN9ug/nor8RD3kw/CJI/j+I7X88wIZVFDVykqC2s5RWS/XfcpBJzgTH7NhhwPt0gU0XpHorhPytv7SmYlZRwlW7rfVDltYXu/3hVtvY5BsPasV2FElphwnsL5tRTaCFfIoiHDdSMMFLg5g+Jo7ziRqw7Clnz7jF0r1SVmcwBD5+TJ/w0AejhYgq/gTzLhsGkmaALiFY9h3LLFXO/Ve9Ne3i4AJ5P22Z4MzZM7YdmN54VVI18rm++2zj24/PeizChDDdHC6eefsP72paPIrH88F4OG1h5CILbmOCAkT8fpvaWut2gwkRcD/pkD4VQgDqvuIMr9wzj84QkbpKrirI2V8sITsCIDK/cnoMpkJMUZQPICGOVFDZZpxXH5SIp08CynrO18p4+XXkkBJGkPA+KwdMHl2E6esXVUXnnQ0PQPbji0d8itYXGh295SH0dlMu88Czxb1mlSrBV0HwhGtXXSx388W/ptkd3YZQaRDCnibd0kpJb2k86v38G4tzbdRPFcMAie2qpbqbC6J7lezOSTsotWNknng0U5YOLLGSyGnnEnBeIHEpZ4zxSmiYj6FhZf919QVuQr7ycKl5aqrlVAQZkhSdBp0oUiRFvKg5I/yq+4RN19eRYrumscROWSXQhFWUbEMTTR7Uv0IOuq6OEScWPTY=
    - secure: UpZmAuIWHZIG2XK4OeDYWLm9/BSKM0HvSZtseZfgdgI3OXKSBfQGpSYVAmxevqT/B1ATEctUupELV42DsghWC5nLa36nYAN4PZZnQWFjmSK2VAgYCWyCKovrGgkH3/5NtZNePy+37wiMZ97jtS1AnNhzHf0JxJ9pdlL21mf2k10tvZj1+AiH9Q73FF1C0X8vJRrBqVPfhiQ1h7SkZfkoppiJB2bU7ZP/IoDlX33NLOntSGg6R563qCEbZddeFFXVqw6WPMYWBpFOVCOVYHWMgfnUmVReq+ZUhWwsMCfYNlrwd4B4qG4Y1DL0T4KhZs+SEpV60ACbgwuWh5UYNV1Y4aZz+cwBZZr9CZnWENhS8iEXAfLDspHMrlPsiSIwU+3QM/Mx0PGad+q+C1YNvNGrKmRJbd9pRt4uuh+Z4ExVj4NxCaOovBQNobkiWCLZD/xDC8X9U3cTOzUUbJmQnZof3LK8Zy8B8tfxMhJEoKe+2Y83yyHgR9uilcsOAwZSwlgzQ0EV8cPWo3FtGJRkC4DKgRoGvOB5tcELNo3dR5JS4P/6NJIrzMKP6V8neUfwhVGNMB5AE6TyIxo9DXhHZowIkBFmpUOy8sjgG/fTWwsOWWn89nc79mNGWEWv9Qsdd39r7ya83zulRqIl8ZBmDxRl//lBaR022VIb9crroerhMSU=
