language: java
jdk:
- openjdk11
cache:
  directories:
  - "$HOME/.m2"
sudo: required
services:
- docker
notifications:
  email:
  - ngomalalibo@gmail.com
  on_success: always
  on_failure: always
addons:
  ssh_known_hosts: ec2-3-64-125-172.eu-central-1.compute.amazonaws.com
before_install:
- chmod +x mvnw
- mvn clean install
- export BUILD_NAME=stockquote-master-$(date -u "+%Y%m%d%H%M%S")
script:
- sh travis_scripts/tag_build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i "all-stock-key-pair.pem" ubuntu@ec2-3-64-125-172.eu-central-1.compute.amazonaws.com
    'bash launch_build.sh'
  on:
    branch: master
env:
  global:
  - secure: khv6MN92V93kaLD9aHfopmu+4dBUnhpVTZBM0I7+cGyHjOSC7J+h+IhkxwxEuJU4JUjJdQ9j0sjKXRkYGUPi7Ku8aAUzLesGKzpuG+HrR4mqMtW5K9Buleu5XqfokQH9d7GvBhMTxuOBfEFhOEDiHRrR/4lRfsyL7zHCfli14a7PpSUTgNW+SR7L0AbhRaXs9W9xIioWMHCB8/Bt35KoHXuOhyH40a/wnSceZR3fAurOuExa6Z4kN8J59hIMzBbhFxfBi9WjQeW7TlznxrakWC1vrFEURWtFztGEIpUtU7ugc+SymDeJ6YDUBURNmtBuqyfDHV9GNaKYHh83wI9DWDdpol0VfkrMkyj46V15SubczuU0W5yOXlmtjXSu9WOa+/yxzh7ZosX2iV/JJt9ySHy6Qhm5ybW15pFWGQ9EAbmBszjGbt/s3ur2xL6ziRgTFJK8ybI4Aucfv6PFkWYbU/sL5oPow88i6GO3AdY1N/A8OWEyls5gsN8g9yRIzrM4iv07phP5kVs1wsCtjybbYKQoJ9z2fispQ1rCZHT6bZTPrJD1M2mlaMm8XE/j5NTbAxMrLaProJ8ThKYb8eituhCBkckkT8D5lPmBtKWwmeelmwZH+Tgqg1X9d8SccMYcGjWP8VMRkSEQD0yurtpC1ntGsJ15PprNlXNVgy2prVg=
  - secure: ilrGjBcAn5hjp+P2Gb1iF9gUl82M0Ml1qFhrcE/x5aVSlTYtt6mynOigJGiDIaSm9Ig6b1M3vHheQxxoGixndK8XaNRyleO9LtNzqwX8GqdB5YQqziEQ7Vk2FAfl6empuIbWmLXfAhYSwuOj8JVPtybJc/h48fVn6YGJaJemb2gDg2uXkg8oaUXh//G8ShmZ0RDMsp+Gf85IZTYQgRtdv9bzeigJ+xzSJTMLZ8O03h3De8TmJ1D33mPKjOAXUQu1XJYYxHIu654DTF2XPkm2UbTNmkNgC4f2bOLX0qNhvd3ozbYWhVR2QD8aTgBexVxEBIvZsfb/2NubgqwU4YnL7CkQcPUuJs10m/WPwV1zmCY2LDg0QNC3WxPDNniXvLGtaPZjeovSLLNuNqczAI0QyPahXeiI2NWT5cwGcnpsgErBSduz4p3OR9kfDqPl3MRduWur9dhnOajrnRg6fcPX4qJNYpdmprGqfFWYVteROwIJzFoCXchAo3zs29xxlUhXbVMarfMT8nDfoseZBxGy9oYLk12DyDHjDw3WFGkOWibfxB3XtsCoQJ7DKr0nUzjCWB+AqYmmNNkrwFs0n1KKCGyB3jijIWVJdR5HL+tTGT5hN2GXcXrrK51PkYZ2ONrFIdtEWkTuDCcjAFwUhA1o+9MYE5xF60loCtZVBAQeBdM=
  - secure: QxPyUWs9dF+eToVSl51OFIAz5UPdquQ/i/oBsq/zNfLVju/0QR8/SrEe7Fzo814ANUgzjMOdJYEJPc1/K703tB6Rwf4ZKdLSI2uEncL8q4izHo5U/rrRv1czzt2UsvpHpIz8+tQaCbh3N+cLWF1oL/2npYg1P1FpBgq7Y2G134xnS78OtB0OAMFmJH9fBstsLmjC4lwwZVWaAroTQTkCTmuIJ5tGpslxOqwyZsAe7Ig7hv+2kys1FDWJn3rKWpDKAoFfHZxMQScv34jcz07iAuW+C1igZGfU054BF/+cds15YFoyc3rCdhF1UCt6WUFNIVaQcBrlUJ8rvGt4XjbfmkjG4JWX0hVNgoB4kh4+YSFZRSCM43Nygmhy7LAAikmR28Nu2Er1m/aCSpdArsIxcT3jXRsTPjvoSavstjQWGo4lGhVodx51E9/aKx4EJfq+onJ7ZGT10HRje5R6dbl2Ai0jLqKss6JJ6w4taT1hITLzCKKF+KumEV9GgUEXhvh+iDUlGRQr2dNd5vLlYO1pcRHEqqr4h2cXwy47D3sU7kV2jvbjRNEjypNCBlgd0VNMvcksACP2mvA2VfZ1Z/C6gxceaOow4TCQSNntlWUhI3AyrtCAZRbcVoQqvt0kWNFbQ175LEvUxP8jAj1G8m3h+9DNQiWN6BSa4EevKDeLFv0=
  - secure: NMpgOACPJ3GB1RKY/8SlkqF2QQxcZhR5VQhY1CBakM3lY5Vt0LazC2RVSuKiCL+UJycjZIuangK5v7jjx43HFgp6hQahpiqtCen/pNvW6Hort3+VWHnOjM26wSjZLpZ7V47q9UV6/DMwAPqic/ObA7AjPgER25XANWQW7TAkburcqeJqTWa5DLrGyrTgeFfrqiAK/XRM7ZK/YngZ29VPH68EIBxdQwueJpCqVc3VaubvpZ/iKZ3agVT+kKzkvSD9JbrQL6LEz+8ovyJR/H+CYPQIn4lTLT+dYswITqNwq6fJeb5+8HFf/xfxFDDDKUFeoWJs9ZBHSjzq2NFI2DZYBsj80roNYVvrv/loKXG7p7bvevNFnNXyFPiR57UstyTmowmH3tGDPtVO8gc9BOarEzpN8j/izdzSBqNybes0hxrepibkXwU2b8uVZme6xvDaAN6g25t9deNReo/dEPWnMfZxruaNPFwkGvwGqVdGzPHJuyZbT8LZDZUZbvOQFC1MrLNdWO695wlc3ZTb+Fzvvnb0Lxb77JuArVr3+fAmi2aYv21gOkgVl2LZKw7DEGb1BULeqI14SXqam52ga2ckN+ISW+ClMO5JfZPpBjDU+vDsc/zvUHw7RrqQA5bwTW6KlWznqyXgaEcySS/CfAIptIEsrSGi7jv8bLsmqHNxF0g=
  - secure: A49WvojYt3dbczCg6QMN3f3iUlnsjdP5113zQqR8u/qDCc/QJkbbArkjBQLJVckOf4bflH4NfAnb/4e7Edbm6wsm7CaxWcW3V4NTX/xmQXGzSdJi7+DQ+vc+9n3K57+PQlWcW26k+G8tn/CY70tgdKnHL/XNqQ8iOUPNReRGg6c4DBfv5+FmIlefN4upSvwgjd6Lfnuh3bGNT0TjEyjEsncXcjk35wNuAJlCvvXO5uKKTNRIz4Q6saS36lIcrWrOirBNCBJBQ03zrE3uhnPDO7DzxnYso5uunlHCxO/sJ0PkX598UcdnP5Q46t/S89KEJBzwEpi0qfSMZe/XFqcZpTED+aeWZrU8403DZ7o5FppBbMO/nBTIq64RbX/AOFMrztmMrRAfa5iGr+9B6bK9HjzmFdMZsQli6uxgvBIGZC0ZoBw2IudK0QWrr2XgtCPkIFfrEinZ4a1Zlnt2NNB1EyoB4Jfta1MxJRxGty/aerctDq/pHfTredOEd4eEHDlr3Sz6OIDH84cAKKqN57taEMRV5hkFSTYIyoa5LPXF1CZg9nNk/8pwzOgZazUBWBhvHG0lVrKqpt0EnBj/2DS2WAMdcwMXXBz3d/ebMjZsPfdFLJb7vqmEE++7oTYbGuLrj3xCtZw6nb8aWQRJKkqYniVHa1Q/u+1+arYIecj37mY=
