language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
sudo: required
services:
  - docker
notifications:
  email:
    - ngomalalibo@gmail.com
  on_success: always
  on_failure: always
addons:
  ssh_known_hosts: ec2-3-64-125-172.eu-central-1.compute.amazonaws.com
before_install:
  - chmod +x mvnw
  - mvn clean install
  - export BUILD_NAME=stockquote-master-$(date -u "+%Y%m%d%H%M%S")
script:
  - sh travis_scripts/tag_build.sh
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i "all-stock-key-pair.pem" ubuntu@ec2-3-64-125-172.eu-central-1.compute.amazonaws.com
    'bash launch_build.sh'
  on:
    branch: master
env:
  global:
    - secure: MkjHwBaUFc+akANjVBkeEy7jLNkDcjdHbPIkEukqitGUMwiCrQNwVXG8G5WFyZVprmDVZlp2IwyiOXwDg/AIPSBseOslCYKzMSipnvKdcsj9QmoOAb1xUNs7s205eB7E4MSKB9mG1XAaUUCZnt3w+8uVD1x69JQHw1szitj4eGICTcKj8jLgLMQtJGTx5nPbZyy4Gx0t26QVC81rlRtTVcSLB5SijyyM1pmYd5oVodvroA9MZxmFn9d9IpUtB5T2qvE9132QIbDa+mrWulhq4pggawgqrjWRTxK5fW1gMDbbWpf3GSRb2Hrrepo+2IZmACTwot989W7NHynlrVF8YmkwytN75oKbNMLR4jTDqlqjgSr2se0k3ksu2Vx9NUFdtKQmStM5V2pDtZxDxAzNCkD5Oo7L9my3Yke7/0ncYKALOZ7rh5zO32PmxK/ikQFf4PUtyTsRsrSwuhkKuIKhHQYyZHWAOeeT4hIIrj+HaYI4o4AY1gAGrcfMdsUnY6uEldd63iYNFSCskyzEpNVRtLnZFK2B5x5+t3fWrO3yzoQxrAovCLlYAg1lifvd7n6h6vJE0buUSbjLxIvLK2+9dtTWM++B2NRZKjz7KBVsP8EQwVboK6jnayKY5j0HwiIMew3tIzj9Lckc4jXuqSx0cl6SmASrp+itBbgeg2kMo4o=
    - secure: ju6ctWj2vnqf1bp8h0kn9GFUCA8Rcd3B9nuVJPQakpqlCmSTmgocx4a1IK/HnZ7PY2JpNSbzwQ/2j4wNV2a7ML6lKvYf+Tz3Il+mCl/4tUMFUr07AZGPJzXsDP1Qy/TuB1V0FRvwpKjBg7bkz8M4pimMYJOIHrkDkW049hoa504OZwmjFTve6VhE/6S0Aw4FRbLRCI6LLSyZvdY7nBTrtHL5s+Na+xpEojMV4sG7J/Rt7DgJiGwsMVu/HUZ/7baUiSkHq05w0HXOn2RXYUmDrf0DiuuDxn7F8Jr0Qiqe6aSC4fOmR0g3qHuvriIR4t/cewp0e+Xm+R3U/4o1gem/cCjV9Y2usWPVaTn4nije2z6S18FaYnKqGj1cDi+8ZDsH4Wav2N4kViozhz8Mw9CaTCqQA4cDOGWfLLGQhoc/eacp29MbzVQCiPtJ+qivm9KCaBP7o2n9s73AEJr/8RwUr35qWLCilQjA1KkTwxdM7v3P5mSfd8Ul/s0/jr0UpTTqGHMnfXnP3FUh4QIMiBM3QfzbTB02crB4wEFugyijzf5BU2AtDCMLpzF996qXapBqa4yMyS/W32QuPtL8NvM9DaXqZah7UEbIlDDgcXGIlXjpTI3ZUFgTFbG/vtCc2tNUpe2kxGtkkK7z3dd6i0/FD94ooiDgbhqXsqjWi6DJCLM=
    - secure: MFiIhQIL+841B9yE2zdO0ZdcTmXixYOvSp7t1Talh2hCOR3DOR3r0rkI5bcP+mjWE/H9LU5GFX9YSjCKJo/IzgDgYM6rwTf6eNpvtPuQ9e9AG82g7S9YgX2H6mPBeQTIcYO65rmYxoeoIChl5PnGrnSQt7HMS4+KGiADWdYQNMQ/F08mJ/EymDdJ5v3MkjEjAoRRLYR2Kxwets+P8VwltL6YBIHPMT8r4sZZL+f0lmL/4r/5f3qEBa4ioWKqMygiQHrgVo7VYHwRG0cdMG7fMbjalGuAlTULAMYHyrmApum7kNdRO7HxK7K5KF4iLHcO6e1QtykJdpqBEr0x4Gnzh+vdaUn7DQkcHlRu9K1Q4ij/ywPSLBZLiUUszWp2sbwQpXBRHkTgXXIdZdQpPhQ2XdbSkCi7DTKOG/0DpOnBasSi1vLfjx3fejy60DFgmSxt0CbpenkzWoJARU5VW3SnagRsSXE2Yfkj0HKDEelMWD0a8qFK17dFyzq6MLuyim4wTthO3PqDCesf9kkwZ5jN+j0eKDFRLV7dpVBF2uSPKlpW63/IDTbmSQiPcLj8Ay0RA8xRfEk0hZ/EJn7sTzd1HF2Ug8csf4IkBhZL3tuxpzQ9QCMiPNoZieeCpXQwXfRvYX0SSQB9V0HJl5K4ewPPppcUvrZNX8fasorD5R3FSbw=
